name: auto-update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.AUTO_UPDATE_TOKEN }}

      - name: Get latest version
        id: boot-version
        run: |
          pip3 install -U lastversion

          UBOOT_VER=$(lastversion --format tag https://github.com/u-boot/u-boot)
          UBOOT_VER=${UBOOT_VER#v}
          OPENSBI_VER=$(lastversion --format tag https://github.com/riscv-software-src/opensbi)
          OPENSBI_VER=${OPENSBI_VER#v}

          echo "tag=v${UBOOT_VER}-${OPENSBI_VER}" >> $GITHUB_OUTPUT
          echo "uboot_ver=${UBOOT_VER}" >> $GITHUB_OUTPUT
          echo "opensbi_ver=${OPENSBI_VER}" >> $GITHUB_OUTPUT

      - name: Check if tag exists
        uses: mukunku/tag-exists-action@v1.5.0
        id: check-tag
        with: 
          tag: ${{ steps.boot-version.outputs.tag }}
          repo: 'cocoa-xu/freebsd-riscv64-vm-boot'
      
      - name: Update if tag not exists
        if: steps.check-tag.outputs.exists == 'false'
        run: |
          cat << EOF > README.md
          # Boot files for riscv64 FreeBSD vm

          This repo auto tracks and releases latest uboot and bios files for running riscv64 FreeBSD vm with qemu-system-riscv64.

          Current latest version:

            - uboot-${{ steps.boot-version.outputs.uboot_ver }}
            - opensbi-${{ steps.boot-version.outputs.opensbi_ver }}
          
          EOF

      - name: git commit and release
        if: steps.check-tag.outputs.exists == 'false'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md || true
          git commit -m "uboot ${{ steps.boot-version.outputs.uboot_ver }} + opensbi ${{ steps.boot-version.outputs.opensbi_ver }}" || true
          git push || true
          git tag ${{ steps.boot-version.outputs.tag }}
          git push origin ${{ steps.boot-version.outputs.tag }}
